export const INITIAL_TRUCKS = [
  // ── WALTER / PRELATĂ ────────────────────────────────────────────────────────
  { id:"AG10003",  remorca:"AG10016",   sofer:"PETRE ION",           telefon:"",            tip:"VOLVO NOU STD",    casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"11.06", loc:"FR52",                    necesar:"Cursă următoare Walter",    obs:"" },
  { id:"AG52LXL",  remorca:"AG66LXL",   sofer:"SUCEA ADRIAN",        telefon:"",            tip:"MERCEDES NOU STD", casa:"WALTER",  ruta:"",      actiune:"ÎNCARCĂ",        data:"12.06", loc:"HU5211",                  necesar:"De anunțat la Walter",      obs:"Pleacă 11.06 din garaj. Desc. 18.06 ES03 Alcoy" },
  { id:"AG54LXL",  remorca:"R6052BCY",  sofer:"PĂIUȘESCU PETRE",     telefon:"",            tip:"MERCEDES NOU STD", casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"12.06", loc:"Barcelona",               necesar:"Preia remorcă prelată Almeria → Walter", obs:"Anunțat național, trebuie ajuns Almeria" },
  { id:"AG43LXL",  remorca:"AG19MML",   sofer:"GRIGORESCU MARIAN",   telefon:"0742129849",  tip:"MERCEDES MEGA",    casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"12.06", loc:"ES43",                    necesar:"",                          obs:"" },
  { id:"AG45LXL",  remorca:"AG43MML",   sofer:"DUMITRU ADRIAN",      telefon:"0767943730",  tip:"MERCEDES MEGA",    casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"11.06", loc:"AT26",                    necesar:"Cursă RO",                  obs:"" },
  { id:"AG47LXL",  remorca:"AG20NYJ",   sofer:"BOBEICA ALEXANDRU",   telefon:"",            tip:"MERCEDES MEGA",    casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"12.06", loc:"DE74",                    necesar:"",                          obs:"" },
  { id:"AG48LXL",  remorca:"AG64LXL",   sofer:"BOBEICA VIOREL",      telefon:"0754580049",  tip:"MERCEDES MEGA",    casa:"WALTER",  ruta:"",      actiune:"ÎNCARCĂ",        data:"",      loc:"ES20",                    necesar:"",                          obs:"ES20 → HU Kecskemet 16.06 → Hajdu??" },
  { id:"AG49LXL",  remorca:"AG10005",   sofer:"GIURGIU NARCIS",      telefon:"",            tip:"MERCEDES MEGA",    casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"",      loc:"FR40 Mont de Marsan",     necesar:"",                          obs:"" },
  { id:"AG28MML",  remorca:"AG79LXL",   sofer:"VILCICA TUDOR",       telefon:"0771793858",  tip:"SCANIA STD",       casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"11.06", loc:"FR62",                    necesar:"",                          obs:"" },
  { id:"AG21MML",  remorca:"AG38MML",   sofer:"GROZEA NICOLAE",      telefon:"0742366977",  tip:"SCANIA STD",       casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"12-15.06", loc:"DE06",               necesar:"",                          obs:"" },
  { id:"AG26MML",  remorca:"AG05MML",   sofer:"BERESCU CLAUDIU",     telefon:"0752133823",  tip:"SCANIA STD",       casa:"WALTER",  ruta:"",      actiune:"DESCARCĂ",       data:"12.06", loc:"DE52 Ubach",              necesar:"",                          obs:"Anunțat la Walter deja" },
  { id:"B152DMT",  remorca:"AG36MML",   sofer:"IORGA GABRIEL",       telefon:"",            tip:"MAN MEGA",         casa:"WALTER",  ruta:"",      actiune:"DISPONIBIL",     data:"",      loc:"Garaj",                   necesar:"Export tur-retur 2 săpt.",  obs:"Pleacă săptămâna asta (provizoriu)" },
  // ── CALICHE / FRIGO ─────────────────────────────────────────────────────────
  { id:"AG04ELD",  remorca:"R6519BCY",  sofer:"BOERU AUREL",         telefon:"",            tip:"VOLVO SH",         casa:"CALICHE", ruta:"",      actiune:"SERVICE",        data:"",      loc:"ES (radiator)",           necesar:"Național spre Barcelona",   obs:"De văzut ce facem cu el" },
  { id:"AG06ELD",  remorca:"AG03PED",   sofer:"TUFEANU NICOLAE",     telefon:"",            tip:"VOLVO SH",         casa:"CALICHE", ruta:"",      actiune:"DESCARCĂ",       data:"11.06", loc:"DE77 Kehl",               necesar:"",                          obs:"" },
  { id:"AG10008",  remorca:"R5807BCY",  sofer:"DUMITRESCU ADRIAN",   telefon:"",            tip:"VOLVO NOU",        casa:"CALICHE", ruta:"",      actiune:"VAMĂ",           data:"12.06", loc:"Frontera",                necesar:"Aștept destinații",         obs:"" },
  { id:"AG50LXL",  remorca:"AG02PED",   sofer:"DINCA IONUT",         telefon:"",            tip:"MERCEDES STD",     casa:"CALICHE", ruta:"",      actiune:"DESCARCĂ",       data:"11.06", loc:"Madrid",                  necesar:"",                          obs:"Înc. Madrid → ES03. Posibil mai face o urcare, chiar din DE" },
  { id:"AG60LXL",  remorca:"R6481BDD",  sofer:"MIHAI GABRIEL",       telefon:"",            tip:"MERCEDES STD",     casa:"CALICHE", ruta:"",      actiune:"ÎNCARCĂ",        data:"11.06", loc:"ES08",                    necesar:"",                          obs:"Carrion → desc. Lugoj + Aricești (vine acasă!)" },
  { id:"AG62LXL",  remorca:"R6053BCY",  sofer:"SOARE ANDREI",        telefon:"",            tip:"MERCEDES STD",     casa:"CALICHE", ruta:"",      actiune:"DESCARCĂ",       data:"11.06", loc:"Leipzig",                 necesar:"",                          obs:"Înc. 12.06 Polonia → Ploiești" },
  { id:"AG63LXL",  remorca:"R2238BCY",  sofer:"ALECU NICOLAE",       telefon:"",            tip:"MERCEDES STD",     casa:"CALICHE", ruta:"",      actiune:"DISPONIBIL",     data:"",      loc:"ES31 Navarra",            necesar:"Cursă urgentă din ES31!",   obs:"Gol fără cursă — de rezolvat urgent" },
];

export const INITIAL_INACTIVE = [
  { id:"AG10056",  remorca:"R6523BCY",  sofer:"DOBRE FLORIAN",       tip:"VOLVO NOU STD",    motiv:"GARAJ",          obs:"Pleacă pe prelată după LP. De vorbit cu Alina — zile libere cuvenite." },
  { id:"AG16FLH",  remorca:"R2184BCY",  sofer:"POPA IOSIF",          tip:"VOLVO NOU STD",    motiv:"GARAJ",          obs:"Pleacă pe prelată. De discutat cu șoferul + văzut ce remorcă îi dăm." },
  { id:"AG57LXL",  remorca:"R6060BCY",  sofer:"DINESCU VIOREL",      tip:"MERCEDES STD",     motiv:"GARAJ",          obs:"De discutat cu șoferul despre plecare pe prelată." },
  { id:"AG58LXL",  remorca:"AG18PED",   sofer:"NEACSU DORU",         tip:"MERCEDES STD",     motiv:"GARAJ",          obs:"Nu e interesat să plece pe prelată. De discutat." },
  { id:"AG10011",  remorca:"PRELATĂ",   sofer:"NEDELEA MIREL",       tip:"VOLVO NOU STD",    motiv:"GARAJ",          obs:"De discutat cu șoferul." },
  { id:"AG31BFT",  remorca:"R4425BCY",  sofer:"FĂRĂ ȘOFER",          tip:"DAF SECOND STD",   motiv:"GARAJ",          obs:"Trasă la gard momentan." },
  { id:"B110LXL",  remorca:"AG61BLK",   sofer:"FĂRĂ ȘOFER",          tip:"MAN MEGA NOU",     motiv:"SERVICE",        obs:"Probleme AdBlue." },
  { id:"AG51BLK",  remorca:"—",         sofer:"FĂRĂ ȘOFER",          tip:"SCANIA MEGA SH",   motiv:"GARAJ",          obs:"" },
  { id:"AG26LXL",  remorca:"—",         sofer:"FĂRĂ ȘOFER",          tip:"VOLVO VECHI",      motiv:"SECHESTRU",      obs:"Fără talon." },
  { id:"AG58DMT",  remorca:"AG79BLK",   sofer:"FĂRĂ ȘOFER",          tip:"VOLVO VECHI",      motiv:"GARAJ",          obs:"" },
  { id:"AG17NML",  remorca:"—",         sofer:"FĂRĂ ȘOFER",          tip:"SCANIA STD",       motiv:"SERVICE",        obs:"Service Scania." },
  { id:"AG61LXL",  remorca:"—",         sofer:"CIURICA MARIAN",      tip:"MERCEDES",         motiv:"SECHESTRU",      obs:"Talon reținut. LP până în iulie." },
];

export const INITIAL_DRIVERS_IMI = [
  { id:1,  sofer:"PETRE ION",           camion:"AG10003",  telefon:"",           imi:false, dataExpirare:"" },
  { id:2,  sofer:"SUCEA ADRIAN",        camion:"AG52LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:3,  sofer:"PĂIUȘESCU PETRE",     camion:"AG54LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:4,  sofer:"GRIGORESCU MARIAN",   camion:"AG43LXL",  telefon:"0742129849", imi:false, dataExpirare:"" },
  { id:5,  sofer:"DUMITRU ADRIAN",      camion:"AG45LXL",  telefon:"0767943730", imi:false, dataExpirare:"" },
  { id:6,  sofer:"BOBEICA ALEXANDRU",   camion:"AG47LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:7,  sofer:"BOBEICA VIOREL",      camion:"AG48LXL",  telefon:"0754580049", imi:false, dataExpirare:"" },
  { id:8,  sofer:"GIURGIU NARCIS",      camion:"AG49LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:9,  sofer:"VILCICA TUDOR",       camion:"AG28MML",  telefon:"0771793858", imi:false, dataExpirare:"" },
  { id:10, sofer:"GROZEA NICOLAE",      camion:"AG21MML",  telefon:"0742366977", imi:false, dataExpirare:"" },
  { id:11, sofer:"BERESCU CLAUDIU",     camion:"AG26MML",  telefon:"0752133823", imi:false, dataExpirare:"" },
  { id:12, sofer:"IORGA GABRIEL",       camion:"B152DMT",  telefon:"",           imi:false, dataExpirare:"" },
  { id:13, sofer:"BOERU AUREL",         camion:"AG04ELD",  telefon:"",           imi:false, dataExpirare:"" },
  { id:14, sofer:"TUFEANU NICOLAE",     camion:"AG06ELD",  telefon:"",           imi:false, dataExpirare:"" },
  { id:15, sofer:"DUMITRESCU ADRIAN",   camion:"AG10008",  telefon:"",           imi:false, dataExpirare:"" },
  { id:16, sofer:"DINCA IONUT",         camion:"AG50LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:17, sofer:"MIHAI GABRIEL",       camion:"AG60LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:18, sofer:"SOARE ANDREI",        camion:"AG62LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:19, sofer:"ALECU NICOLAE",       camion:"AG63LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:20, sofer:"DOBRE FLORIAN",       camion:"AG10056",  telefon:"",           imi:false, dataExpirare:"" },
  { id:21, sofer:"POPA IOSIF",          camion:"AG16FLH",  telefon:"",           imi:false, dataExpirare:"" },
  { id:22, sofer:"DINESCU VIOREL",      camion:"AG57LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:23, sofer:"NEACSU DORU",         camion:"AG58LXL",  telefon:"",           imi:false, dataExpirare:"" },
  { id:24, sofer:"NEDELEA MIREL",       camion:"AG10011",  telefon:"",           imi:false, dataExpirare:"" },
  { id:25, sofer:"CIURICA MARIAN",      camion:"AG61LXL",  telefon:"",           imi:false, dataExpirare:"" },
];

export const INITIAL_TODOS = [
  { id:1,  text:"🚨 AG63LXL — Gol în ES31 Navarra, cursă urgentă!",                         prio:"red",    done:false },
  { id:2,  text:"🚨 AG04ELD — În service ES (radiator), național spre Barcelona",            prio:"red",    done:false },
  { id:3,  text:"🚨 AG45LXL — Cursă RO după desc. AT26 (11.06)",                            prio:"red",    done:false },
  { id:4,  text:"AG10003 — Cursă următoare Walter după desc. FR52 (11.06)",                 prio:"orange", done:false },
  { id:5,  text:"AG54LXL — Ajuns Almeria, preluat remorcă prelată, anunțat Walter",         prio:"orange", done:false },
  { id:6,  text:"AG52LXL — Anunțat la Walter (pleacă 11.06 din garaj, înc. 12.06 HU5211)", prio:"orange", done:false },
  { id:7,  text:"AG10008 — Frontera 12.06, aștept destinații de la Caliche",                prio:"orange", done:false },
  { id:8,  text:"B152DMT / Iorga — Export tur-retur 2 săptămâni, pleacă săpt. asta",        prio:"orange", done:false },
  { id:9,  text:"AG10056 / Dobre — Vorbit cu Alina, zile libere cuvenite + plan prelată",   prio:"blue",   done:false },
  { id:10, text:"AG16FLH / Popa Iosif — Discutat plecare prelată + remorcă",                prio:"blue",   done:false },
  { id:11, text:"AG57LXL / Dinescu — Discutat plecare prelată",                             prio:"blue",   done:false },
  { id:12, text:"AG58LXL / Neacsu — Discutat plecare prelată (nu e interesat)",             prio:"blue",   done:false },
  { id:13, text:"AG10011 / Nedelea Mirel — Discutat plecare",                               prio:"blue",   done:false },
];

export const ACTIUNI = ["ÎNCARCĂ","DESCARCĂ","VAMĂ","ÎN DRUM ACASĂ","PAUZĂ","DISPONIBIL","SERVICE","—"];
export const MOTIVE_INACTIVE = ["GARAJ","SERVICE","SECHESTRU","FĂRĂ ȘOFER","FĂRĂ ACTE","ALTELE"];
